import { ServiceCategory } from "@prisma/client";

export const serviceCatalog = [
  // ─── BEAUTY ──────────────────────────────────────────────────────────────────
  {
    slug: "signature-color",
    name: "Color Signature + Brushing Couture",
    category: ServiceCategory.BEAUTY,
    description:
      "Diagnóstico editorial, color premium, sellado y peinado impecable para habitación o domicilio.",
    basePrice: 79000,
    durationMinutes: 150,
    supportsHairMetrics: true,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: true,
  },
  {
    slug: "extensions-luxe",
    name: "Extensiones Luxe Match",
    category: ServiceCategory.BEAUTY,
    description:
      "Instalación de extensiones con adaptación personalizada según largo, abundancia y objetivo de look.",
    basePrice: 119000,
    durationMinutes: 180,
    supportsHairMetrics: true,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: true,
  },
  {
    slug: "hair-restore-ritual",
    name: "Ritual de Restauración Capilar",
    category: ServiceCategory.BEAUTY,
    description:
      "Limpieza profunda, reconstrucción y terapia de brillo con protocolo de recuperación premium.",
    basePrice: 59000,
    durationMinutes: 90,
    supportsHairMetrics: true,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "balayage-editorial",
    name: "Balayage Editorial",
    category: ServiceCategory.BEAUTY,
    description:
      "Técnica de balayage personalizada con degradé natural, acabado luminoso y sellado de brillo.",
    basePrice: 95000,
    durationMinutes: 180,
    supportsHairMetrics: true,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: true,
  },
  {
    slug: "keratin-couture",
    name: "Keratina Couture Premium",
    category: ServiceCategory.BEAUTY,
    description:
      "Tratamiento de keratina con proteínas de seda. Alisado duradero, sin agresión química, con sellado editorial.",
    basePrice: 89000,
    durationMinutes: 150,
    supportsHairMetrics: true,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "brushing-premium",
    name: "Brushing & Finishing Premium",
    category: ServiceCategory.BEAUTY,
    description:
      "Lavado, tratamiento hidratante, secado y peinado de acabado para cualquier ocasión o sesión de fotos.",
    basePrice: 35000,
    durationMinutes: 60,
    supportsHairMetrics: true,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "highlights-luxury",
    name: "Mechas Luxury Foil",
    category: ServiceCategory.BEAUTY,
    description:
      "Mechas en papel foil con colorimetría personalizada, tratamiento post-color y brushing de terminación.",
    basePrice: 85000,
    durationMinutes: 165,
    supportsHairMetrics: true,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "hair-gloss",
    name: "Gloss de Brillo Capilar",
    category: ServiceCategory.BEAUTY,
    description:
      "Terapia semipermanente de gloss para potenciar el color, intensificar el brillo y suavizar la fibra capilar.",
    basePrice: 42000,
    durationMinutes: 75,
    supportsHairMetrics: true,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },

  // ─── WELLNESS ────────────────────────────────────────────────────────────────
  {
    slug: "deep-tissue-massage",
    name: "Masaje Deep Relief",
    category: ServiceCategory.WELLNESS,
    description:
      "Masaje descontracturante o relajante con ambientación tipo spa, aromaterapia y ritual de cierre.",
    basePrice: 65000,
    durationMinutes: 75,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: true,
  },
  {
    slug: "hotel-spa-experience",
    name: "Hotel Spa Experience",
    category: ServiceCategory.WELLNESS,
    description:
      "Pack curado para hoteles: masaje, facial express y styling de terminación premium en habitación.",
    basePrice: 129000,
    durationMinutes: 150,
    supportsHairMetrics: false,
    supportsHome: false,
    supportsHotel: true,
    isFeatured: true,
  },
  {
    slug: "swedish-massage",
    name: "Masaje Sueco Relajante",
    category: ServiceCategory.WELLNESS,
    description:
      "Masaje de relajación total con técnica sueca, aceites esenciales premium y ritual de aromaterapia.",
    basePrice: 58000,
    durationMinutes: 60,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "couples-ritual",
    name: "Ritual de Pareja Premium",
    category: ServiceCategory.WELLNESS,
    description:
      "Experiencia simultánea para dos: masajes sincrónicos, ambiente curado y protocolo de cierre con champagne.",
    basePrice: 148000,
    durationMinutes: 90,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: true,
  },
  {
    slug: "prenatal-massage",
    name: "Masaje Prenatal y Postparto",
    category: ServiceCategory.WELLNESS,
    description:
      "Técnica adaptada para embarazo o puerperio: posiciones seguras, aceites seguros y enfoque en recuperación.",
    basePrice: 62000,
    durationMinutes: 60,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "aromatherapy-session",
    name: "Sesión Aromaterapia & Energética",
    category: ServiceCategory.WELLNESS,
    description:
      "Combinación de masaje liviano, difusión de aceites esenciales y técnica de puntos energéticos para equilibrio profundo.",
    basePrice: 55000,
    durationMinutes: 60,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },

  // ─── SKINCARE ────────────────────────────────────────────────────────────────
  {
    slug: "facial-glow-ritual",
    name: "Facial Glow Ritual",
    category: ServiceCategory.SKINCARE,
    description:
      "Limpieza, exfoliación, activos hidratantes y masaje facial para piel luminosa y descansada.",
    basePrice: 54000,
    durationMinutes: 60,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: true,
  },
  {
    slug: "anti-aging-facial",
    name: "Facial Antienvejecimiento Signature",
    category: ServiceCategory.SKINCARE,
    description:
      "Protocolo antiedad con vitamina C, retinol y masaje linfático. Resultados visibles desde la primera sesión.",
    basePrice: 72000,
    durationMinutes: 75,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "hyaluronic-facial",
    name: "Facial Ácido Hialurónico",
    category: ServiceCategory.SKINCARE,
    description:
      "Hidratación profunda con activos de ácido hialurónico de alta concentración y masaje de drenaje facial.",
    basePrice: 65000,
    durationMinutes: 60,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },

  // ─── NAILS ───────────────────────────────────────────────────────────────────
  {
    slug: "manicure-premium",
    name: "Manicura Premium",
    category: ServiceCategory.NAILS,
    description:
      "Manicura completa con remoción, limado, cutículas, base nutritiva y esmalte semipermanente a elección.",
    basePrice: 28000,
    durationMinutes: 60,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "pedicure-deluxe",
    name: "Pedicura Deluxe",
    category: ServiceCategory.NAILS,
    description:
      "Pedicura con exfoliación, hidratación, masaje de pies y esmalte semipermanente. Incluye peeling de talones.",
    basePrice: 32000,
    durationMinutes: 70,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "gel-nails",
    name: "Uñas de Gel Premium",
    category: ServiceCategory.NAILS,
    description:
      "Colocación o reconstrucción de uñas en gel de larga duración con diseño personalizado y acabado editorial.",
    basePrice: 45000,
    durationMinutes: 90,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "nail-art-editorial",
    name: "Nail Art Editorial",
    category: ServiceCategory.NAILS,
    description:
      "Diseño artístico de uñas con técnicas de nail art: stamping, gradiente, pedrería y arte inspirado en pasarela.",
    basePrice: 55000,
    durationMinutes: 100,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: true,
  },

  // ─── MAKEUP ──────────────────────────────────────────────────────────────────
  {
    slug: "event-makeup",
    name: "Maquillaje para Evento",
    category: ServiceCategory.MAKEUP,
    description:
      "Maquillaje profesional adaptado a la ocasión: cóctel, gala, reunión o sesión fotográfica con acabado duradero.",
    basePrice: 48000,
    durationMinutes: 60,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "bridal-makeup",
    name: "Maquillaje Nupcial Couture",
    category: ServiceCategory.MAKEUP,
    description:
      "Sesión completa de maquillaje nupcial con prueba previa, airbrush HD y resistencia hasta 12 horas.",
    basePrice: 95000,
    durationMinutes: 120,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: true,
  },
  {
    slug: "express-makeup",
    name: "Maquillaje Express Luminoso",
    category: ServiceCategory.MAKEUP,
    description:
      "Maquillaje natural o glam express en 30 minutos. Ideal para reuniones, eventos de medio día o salida de noche.",
    basePrice: 32000,
    durationMinutes: 35,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },

  // ─── BODY TREATMENTS ────────────────────────────────────────────────────────
  {
    slug: "body-exfoliation",
    name: "Exfoliación Corporal Premium",
    category: ServiceCategory.BODY_TREATMENTS,
    description:
      "Exfoliación profunda con sal marina, aceites esenciales y aplicación de manteca corporal de karité.",
    basePrice: 58000,
    durationMinutes: 70,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "chocolate-wrap",
    name: "Envoltura Corporal de Chocolate",
    category: ServiceCategory.BODY_TREATMENTS,
    description:
      "Envoltura térmica con cacao puro, arcilla y aceite de argán. Suavidad y nutrición profunda para todo el cuerpo.",
    basePrice: 68000,
    durationMinutes: 80,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: false,
  },
  {
    slug: "detox-body-ritual",
    name: "Ritual Detox Corporal",
    category: ServiceCategory.BODY_TREATMENTS,
    description:
      "Sesión de drenaje linfático manual, exfoliación enzimática y envoltura detox con algas marinas premium.",
    basePrice: 75000,
    durationMinutes: 90,
    supportsHairMetrics: false,
    supportsHome: true,
    supportsHotel: true,
    isFeatured: true,
  },
] as const;
